Fix: API response for activating users returns 403 Forbidden
anitab-org/open-source-programs-backend pull request #108
Opened 2021-03-01 09:41 UTC by Amulya-coder

### Description

Adding the decorators separately to make the activation method available without any auth credentials.

Fixes #81 

### Type of Change:

- Code

**Code/Quality Assurance Only**
- Bugfix (non-breaking change which fixes an issue)

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings

2021-03-01 09:41 UTC, Amulya-coder commented
@codesankalp can you please review it

2021-03-01 18:00 UTC, codesankalp requested changes
QA-Checks and tests are showing as queued. Please make the suggested changes and let's see if the workflow runs again or not. @Amulya-coder

2021-03-01 18:00 UTC, codesankalp commented on token_auth/views/register.py
> +            return Response({"Invalid link"}, status=status.HTTP_400_BAD_REQUEST)
A blank line is needed at the end of the file @Amulya-coder

2021-03-01 18:53 UTC, Amulya-coder commented
@codesankalp it's still failing!

2021-03-01 19:07 UTC, Amulya-coder commented
In my terminal, it's showing some errors like `pylint(import-error)` can this may be the reason?

2021-03-02 05:47 UTC, codesankalp commented
@Amulya-coder Follow the guidelines mentioned in README for QA-Checks and Testing.
And according to the workflows test Black check and Flake8 check are failing.

2021-03-03 13:33 UTC, Amulya-coder commented
@codesankalp I have run black-checks and flake-checks everything looks fine. I think failing test isn't a major problem for this issue we can ignore this.

2021-03-03 13:34 UTC, codesankalp commented
@Amulya-coder This PR can't be merged if tests (QA-checks) do not pass.

2021-03-03 13:35 UTC, codesankalp commented
You can use the suggestions as mentioned in the actions.

2021-03-03 13:38 UTC, Amulya-coder commented
Ok @codesankalp I will try once again.

2021-03-03 14:01 UTC, Amulya-coder commented
@codesankalp QA checks are passed 👍

![image](https://user-images.githubusercontent.com/66437295/109816676-01417c80-7c57-11eb-9a3d-7c3614e138fe.png)

2021-03-03 14:21 UTC, Amulya-coder commented
@codesankalp now can you please approve this.

2021-03-03 16:16 UTC, codesankalp submitted a review, later dismissed
@Amulya-coder LGTM :tada: 
**Code Review**: Done 
**Testing**

**Screenshots**
![image](https://user-images.githubusercontent.com/56037184/109835653-6a31f000-7c69-11eb-94ca-bb29dc222636.png)


![image](https://user-images.githubusercontent.com/56037184/109835800-8fbef980-7c69-11eb-9df6-ea4d87f27f89.png)


![image](https://user-images.githubusercontent.com/56037184/109835512-453d7d00-7c69-11eb-8678-319150c4551f.png)

2021-03-04 19:05 UTC, codesankalp commented
@isabelcosta Needs your review in this PR.

2021-03-16 11:58 UTC, devkapilbansal submitted a review, later dismissed
LGTM :+1:

2021-03-16 18:14 UTC, codesankalp commented
I have tested it and it is working fine @devkapilbansal.
Can you test it also, so that I can add a ready to merge label?

2021-03-16 20:01 UTC, devkapilbansal commented
Adding `Ready to Merge` since this is already been tested above.

2021-03-16 20:03 UTC, codesankalp commented
Thanks, @Amulya-coder for your contribution. :rocket:

2021-03-20 14:21 UTC, isabelcosta commented
@Amulya-coder @codesankalp @devkapilbansal this is failing the tests, why is that 🤔

2021-03-20 16:27 UTC, codesankalp commented
@isabelcosta You can trigger the workflow again but the workflow will fail due to a secret-key error.

2021-03-20 16:28 UTC, codesankalp commented
After merging of this https://github.com/anitab-org/anitab-forms-backend/pull/109
You can trigger the workflow again and it will pass.

2021-03-20 18:29 UTC, Amulya-coder commented
@isabelcosta locally it will pass all the build tests I have checked, here it shows due to the secret key as github requires the API key to trigger the workflow which is resolved by the codesankalp in #109

2021-04-02 15:54 UTC, isabelcosta commented
@Amulya-coder can you please update the branch? So the tests will pass?

2021-04-02 18:02 UTC, Amulya-coder commented
ok @isabelcosta I will update it by tomorrow.

2021-04-09 19:17 UTC, Amulya-coder commented
@isabelcosta I have updated the branch, can you please review it, sorry for the delay.

2021-04-14 15:14 UTC, codesankalp approved these changes

2021-04-14 21:13 UTC, isabelcosta approved these changes
Cool! Thank you for your contribution @Amulya-coder 🎉

2021-04-14 21:15 UTC, isabelcosta commented
I will merge because latest changes were only to style with black formatting, and this was tested already by @codesankalp 🚀

2021-04-14 21:15 UTC, merged