fix: Replace all occurrences of open-source-programs-backend (#120)
anitab-org/open-source-programs-backend pull request #121
Opened 2021-03-10 06:52 UTC by HeroicHitesh

### Description

Replace all occurrences of `open-source-programs-backend` with `anitab-forms-backend`

Fixes #120 

### Type of Change:

- Documentation

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

2021-03-11 07:36 UTC, codesankalp submitted a review, later dismissed
@HeroicHitesh Good Work :+1:.
I hope there are no `open-source-programs-backend` after this.
But thanks for your contribution.

2021-04-02 18:49 UTC, devkapilbansal submitted a review, later dismissed
LGTM :+1:

2021-04-02 22:02 UTC, isabelcosta commented on README.md
> +For more information, you can read [backend project wiki](https://github.com/anitab-org/anitab-forms-backend/wiki) and the [web project wiki](https://github.com/anitab-org/open-source-programs-web/wi
```suggestion
For more information, you can read [backend project wiki](https://github.com/anitab-org/anitab-forms-backend/wiki) and the [web project wiki](https://github.com/anitab-org/anitab-forms-web/wiki).
```

2021-04-02 22:03 UTC, isabelcosta commented on osp-backend-docusaurus/docs/2020-Bismita-Guha.md
> +- **What have you accomplished this week (list specific items accomplished)?**<br/><br/>1. Worked on PRs [#32](https://github.com/anitab-org/open-source-programs-web/pull/32), [#35](https://github.co
```suggestion
- **What have you accomplished this week (list specific items accomplished)?**<br/><br/>1. Worked on PRs [#32](https://github.com/anitab-org/anitab-forms-web/pull/32), [#35](https://github.com/anitab-org/anitab-forms-web/pull/35), [#27](https://github.com/anitab-org/anitab-forms-backend/pull/27) & [#25](https://github.com/anitab-org/anitab-forms-backend/pull/25)<br/>2. Worked on reviews by mentors on Previous PRs<br/>3. Attended Team Meeting for OSP<br/>4. Attended Work Session with Abha and Siddharth<br/>5. Attended 1:1 with Abha, Siddharth & Monal<br/>6. Worked on Weekly Blog<br/><br/>
```

2021-04-02 22:03 UTC, isabelcosta commented on osp-backend-docusaurus/docs/2020-Bismita-Guha.md
> +- **What have you accomplished this week (list specific items accomplished)?**<br/><br/>1. Worked on PRs [#28](https://github.com/anitab-org/anitab-forms-backend/pull/28), [#35](https://github.com/an
```suggestion
- **What have you accomplished this week (list specific items accomplished)?**<br/><br/>1. Worked on PRs [#28](https://github.com/anitab-org/anitab-forms-backend/pull/28), [#35](https://github.com/anitab-org/anitab-forms-web/pull/35) & [#36](https://github.com/anitab-org/anitab-forms-web/pull/36)<br/>2. Work ongoing on issue [#19](https://github.com/anitab-org/anitab-forms-web/issues/19)<br/>3. Attended 1:1 with May, Monal, Abha & Siddharth<br/>4. Attended Work Session with Mentors<br/>Attended Team Meeting for OSP<br/>5. Speed up the work on the Documentation<br/>6. Attended extra meeting with Monal and Abha<br/>7. Fill in First evaluation<br/><br/>
```

2021-04-02 22:05 UTC, isabelcosta commented on osp-backend-docusaurus/docs/2020-Bismita-Guha.md
> +- **What have you accomplished this week (list specific items accomplished)?**<br/><br/>1. Worked on PRs [#28](https://github.com/anitab-org/anitab-forms-backend/pull/28), [#39](https://github.com/an
```suggestion
- **What have you accomplished this week (list specific items accomplished)?**<br/><br/>1. Worked on PRs [#28](https://github.com/anitab-org/anitab-forms-backend/pull/28), [#39](https://github.com/anitab-org/anitab-forms-web/pull/39) & [#40](https://github.com/anitab-org/anitab-forms-web/pull/40)<br/>2. Worked on issues [#12](https://github.com/anitab-org/anitab-forms-web/issues/12), [#13](https://github.com/anitab-org/anitab-forms-web/issues/13) & [#8](https://github.com/anitab-org/anitab-forms-backend/issues/8)<br/>3. Attended Team Meeting and Work Session<br/>4. Attended 1:1 with May, Monal, Abha & Siddharth<br/>5. Worked on Documentation<br/>6. Created issues for the community<br/><br/>
```

2021-04-02 22:05 UTC, isabelcosta commented on osp-backend-docusaurus/docs/2020-Bismita-Guha.md
> +- **What have you accomplished this week (list specific items accomplished)?**<br/><br/>1. Worked on PRs [#39](https://github.com/anitab-org/open-source-programs-web/pull/39), [#40](https://github.co
```suggestion
- **What have you accomplished this week (list specific items accomplished)?**<br/><br/>1. Worked on PRs [#39](https://github.com/anitab-org/anitab-forms-web/pull/39), [#40](https://github.com/anitab-org/anitab-forms-web/pull/40) & [#29](https://github.com/anitab-org/anitab-forms-backend/pull/29)<br/>2. Attended Team Meeting and Work Session<br/>3. Attended 1:1 with May, Monal, Abha & Siddharth<br/>4. Worked on Documentation<br/>5. Created issues for the community<br/><br/>
```

2021-04-02 22:06 UTC, isabelcosta commented on osp-backend-docusaurus/docs/Fork,-Clone,-Remote-and-Pull-Request.md
> +Now that you have setup the project, you need to search for anything to work on which interests you. Have a look at the [Backend Issues](https://github.com/anitab-org/anitab-forms-backend/issues) or
```suggestion
Now that you have setup the project, you need to search for anything to work on which interests you. Have a look at the [Backend Issues](https://github.com/anitab-org/anitab-forms-backend/issues) or [Frontend Issues](https://github.com/anitab-org/anitab-forms-web/issues), whichever interests you. 
```

2021-04-02 22:07 UTC, isabelcosta commented on osp-backend-docusaurus/docs/2020-Bismita-Guha.md
> +- **What have you accomplished this week (list specific items accomplished)?**<br/><br/>1. Worked on PRs [#41](https://github.com/anitab-org/open-source-programs-web/pull/41) & [#31](https://github.c
```suggestion
- **What have you accomplished this week (list specific items accomplished)?**<br/><br/>1. Worked on PRs [#41](https://github.com/anitab-org/anitab-forms-web/pull/41) & [#31](https://github.com/anitab-org/anitab-forms-backend/pull/31)<br/>2. Worked on Issues[#11](https://github.com/anitab-org/anitab-forms-backend/issues/11), [#12](https://github.com/anitab-org/anitab-forms-backend/issues/12), [#8](https://github.com/anitab-org/anitab-forms-web/issues/8), [](https://github.com/anitab-org/anitab-forms-web/issues/9) & [#10](https://github.com/anitab-org/anitab-forms-web/issues/10)<br/>3. Attended Team Meeting and Work Session<br/>4. Attended 1:1 with May, Monal, Abha & Siddharth<br/>5. Worked on Documentation<br/>6. Created issues for the community<br/><br/>
```

2021-04-02 22:09 UTC, isabelcosta requested changes
Thank you for contributing @HeroicHitesh !

I noticed, some references to open source programs still, I made suggestions, feel free to apply them. I think I got all occurrences. I also saw some occurrences from the zulip channel, but that could be done on another issue.

Could you please make the changes and I can then approve?

2021-04-03 03:44 UTC, HeroicHitesh commented
> I noticed, some references to open source programs still

@isabelcosta Actually, the issue mentioned removing occurrences of `open-source-programs-backend` so earlier I replaced them only
> Could you please make the changes and I can then approve?

Now, I have removed occurrences of `open-source-programs` too. Let me know if anything still doesn't look right.

2021-04-03 15:26 UTC, isabelcosta commented
@HeroicHitesh so sorry 😅 I did not notice that little requirement. Will approve :)

2021-04-03 15:27 UTC, isabelcosta approved these changes
Amazing work @HeroicHitesh !
Thank you for your contribution!

2021-04-03 16:42 UTC, codesankalp approved these changes
LGTM :tada:

2021-04-03 16:45 UTC, merged