fixed #139
anitab-org/open-source-programs-backend pull request #147
Opened 2021-06-19 09:15 UTC by untari

### Description

Change title in main heading in *README*, *contact us* to current repository name and fixed format text link in *docs*. No dependencies needed tare required for this change.

Fixes #ISSUE

### Type of Change:
- Documentation

2021-06-19 17:33 UTC, codesankalp commented
@untari Please update the PR description and title to something relevant and meaningful.

2021-06-19 17:34 UTC, codesankalp requested changes

2021-06-19 17:34 UTC, codesankalp commented on README.md
> +# Anitab Forms Backends
```suggestion
# Anitab Forms Backend
```

2021-08-17 20:55 UTC, isabelcosta commented on README.md
> +You can reach the admins, maintainers and our community on [AnitaB.org Open Source Zulip](https://anitab-org.zulipchat.com/). If you are interested in contributing to the OSP project, you may join th
```suggestion
You can reach the admins, maintainers and our community on [AnitaB.org Open Source Zulip](https://anitab-org.zulipchat.com/). If you are interested in contributing to the OSP project, you may join the stream [#anitab-forms](https://anitab-org.zulipchat.com/#narrow/stream/237907-open-source-progs) and ask questions or intereact with the community. Join Us!
```

2021-08-17 20:56 UTC, isabelcosta approved these changes
Thank you for contributing @untari 💯

2021-08-18 02:13 UTC, codesankalp approved these changes

2021-10-01 19:36 UTC, merged