Migrate docs gh pages
anitab-org/open-source-programs-backend pull request #159
Opened 2021-10-17 19:33 UTC by WizardLemon

### Description

Migrating docusaurus deployment from surge to GitHub pages.
Referenced from: https://github.com/anitab-org/mentorship-backend/commit/4cc78ae
Also referenced: https://docusaurus.io/docs/deployment#triggering-deployment-with-github-actions

The check part of the workflow works, but I'm having trouble with deployment, I probably have to fiddle around some more with setting up the secret key on my own repository properly.

For deployment the secret `GH_PAGES_DEPLOY` needs to be added. I have not been successful with trying this out on my own repository, I'll keep investigating some more tomorrow.

**Update:** I've successfully managed to deploy the docs to https://wizardlemon.github.io/anitab-forms-backend/
The problem was that the docusaurus config file needed to be updated as well.

Fixes #127

### Type of Change:

- Quality Assurance
- Documentation

**Code/Quality Assurance Only**
- This change requires a documentation update (software upgrade on readme file)

### How Has This Been Tested?

I've tested the workflow by creating a PR to my own develop branch, the checks run successfuly. I then merged the file to test the deployment, but I have issues with deployment that I think are related to secret keys.

**Update:** I've successfully managed to deploy the docs to https://wizardlemon.github.io/anitab-forms-backend/
The problem was that the docusaurus config file needed to be updated as well.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

2021-10-17 20:26 UTC, wizardlekic commented
I've managed to successfully deploy the documentation to https://wizardlemon.github.io/anitab-forms-backend/ using the workflow actions after updating the docusaurus config file.

2021-10-17 20:40 UTC, isabelcosta submitted a review, later dismissed
Great work! Thank you for providing a lot of context in the PR description ⭐ That is really great!

Thank you for your contribution @WizardLemon !

2021-10-18 05:21 UTC, codesankalp requested changes
@WizardLemon See my comments :point_down:

2021-10-18 05:21 UTC, codesankalp commented on .github/workflows/docs.yml
> +          npm run deploy
blank line at the end of file

2021-10-18 05:21 UTC, codesankalp commented on .github/workflows/docs.yml
> +          git config --global user.name "gh-actions"
```suggestion
          git config --global user.email "opensource@anitab.org"
          git config --global user.name "anitab-org"
```

2021-10-18 05:21 UTC, codesankalp commented on osp-backend-docusaurus/docusaurus.config.js
>    title: 'Open Source Programs Backend Docs',
```suggestion
  title: 'Anitab forms backend Docs',
```

2021-10-18 05:21 UTC, codesankalp commented on osp-backend-docusaurus/docusaurus.config.js
>    tagline: 'Documentation for Open Source Programs Backend',
```suggestion
  tagline: 'Documentation for Anitab Forms Backend',
```

2021-10-18 05:21 UTC, codesankalp commented on osp-backend-docusaurus/docusaurus.config.js
> +  url: 'https://anitab-org.github.io/anitab-forms-backend/',
```suggestion
  url: 'https://anitab-org.github.io',
```

2021-10-18 07:01 UTC, wizardlekic commented
@codesankalp thanks for taking a thorough look and suggesting improvements, I've implemented the requested changes

2021-10-18 07:36 UTC, codesankalp commented on .github/workflows/docs.yml
> +          cd osp-backend-docusaurus/
One more change I forgot to mention in the previous review, as we are not using osp-backend anymore, you can rename this directory in root directory as well as here with anitab-forms-backend.

2021-10-21 19:55 UTC, WizardLemon commented
It seems I've had some conflicts after the newest changes, I've rebased my branch on top of those changes and updated accordingly.

2021-10-22 08:49 UTC, isabelcosta approved these changes
Looks good to me :) Thank you for working on this @WizardLemon 🙌🏾

2022-10-28 21:37 UTC, closed without merging