docs: Update README with link for API docs
anitab-org/open-source-programs-backend pull request #27
Opened 2020-06-23 22:14 UTC by bismitaguha

### Description

- Update README with link for API docs

Fixes #16 

### Type of Change:

- Quality Assurance
- Documentation

**Code/Quality Assurance Only**
- This change requires a documentation update (software upgrade on readme file)

### How Has This Been Tested?

N/A

### Checklist:

- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [x] Any dependent changes have been published in downstream modules

2020-06-24 10:31 UTC, Monal5031 approved these changes

2020-06-24 17:07 UTC, abha224 approved these changes

2020-06-25 13:10 UTC, sidvenu requested changes

2020-06-25 13:10 UTC, sidvenu commented on README.md
> +- [Postman Docs](https://documenter.getpostman.com/view/11324046/Szzoaw1q?version=latest#1fbeb4c3-5540-40a8-b205-380ca7232c59)
```suggestion
- [Postman Docs](https://documenter.getpostman.com/view/11324046/Szzoaw1q?version=latest)
```

2020-06-25 16:29 UTC, bismitaguha commented
@sidvenu I have changed the URL and verified.

2020-06-28 14:03 UTC, merged